language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq gfortran libatlas-base-dev python-numpy
install:
  - pip install ipython mock pandas flake8 --use-mirrors
script:
  - flake8 --exclude=colors.py,_compat.py vincent
  - nosetests
